package org.jcd2052.core.browser.browser;

import com.microsoft.playwright.BrowserContext;
import com.microsoft.playwright.options.Cookie;
import lombok.Getter;
import lombok.Setter;
import org.jcd2052.core.browser.browser.interfaces.IBrowserTab;
import org.jcd2052.core.browser.browser.interfaces.IBrowserWindow;

import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Concrete implementation of the {@link IBrowserWindow} interface.
 * <p>
 * This class wraps a Playwright {@link BrowserContext}, representing an isolated
 * browser session (window) that manages its own collection of tabs (pages).
 */
@Getter
public class BrowserWindow implements IBrowserWindow {
    /**
     * The underlying Playwright BrowserContext associated with this window.
     * <p>
     * Note: The getter is automatically generated by Lombok's class-level {@code @Getter} annotation.
     */
    private final BrowserContext browserContext;

    /**
     * The currently active tab within this browser window.
     * <p>
     * Note: The getter and setter are automatically generated by Lombok's annotations.
     */
    @Setter
    private IBrowserTab currentBrowserTab;

    /**
     * Constructs a new {@code BrowserWindow} instance.
     *
     * @param context The Playwright {@link BrowserContext} to be wrapped and managed by this window.
     */
    public BrowserWindow(BrowserContext context) {
        this.browserContext = context;
    }

    /**
     * Opens a new tab (Page) within this specific browser window context,
     * sets it as the currently active tab, and returns it.
     *
     * @return The newly created {@link IBrowserTab}.
     */
    @Override
    public IBrowserTab openNewTab() {
        IBrowserTab browserTab = new BrowserTab(browserContext.newPage());
        setCurrentBrowserTab(browserTab);
        return browserTab;
    }

    /**
     * Retrieves all currently open tabs within this browser window context.
     *
     * @return A collection of {@link IBrowserTab} objects currently open in this window.
     */
    @Override
    public Collection<IBrowserTab> getBrowserTabs() {
        return browserContext.pages()
                .stream()
                .map(BrowserTab::new)
                .collect(Collectors.toList());
    }

    @Override
    public void addCookies(List<Cookie> cookies) {
        browserContext.addCookies(cookies);
    }

    @Override
    public List<Cookie> getCookies() {
        return browserContext.cookies();
    }

    @Override
    public void clearCookies() {
        browserContext.clearCookies();
    }

    /**
     * Brings the specified tab to the front (makes it visible) and sets it
     * as the active tab for this window.
     *
     * @param tab The {@link IBrowserTab} to switch to.
     */
    @Override
    public void switchToTab(IBrowserTab tab) {
        tab.getPage().bringToFront();
        currentBrowserTab = tab;
    }

    @Override
    public void closeWindow() {
        browserContext.close();
    }
}