package org.jcd2052.core.browser.browser;

import com.microsoft.playwright.Page;
import lombok.Getter;
import org.jcd2052.core.browser.browser.interfaces.IAlert;
import org.jcd2052.core.browser.browser.interfaces.IBrowserTab;
import org.jcd2052.core.browser.browser.interfaces.IMouseActions;
import org.jcd2052.core.browser.browser.interfaces.IStorageManager;

import java.util.function.Consumer;

/**
 * Concrete implementation of the {@link IBrowserTab} interface.
 * <p>
 * This class serves as a wrapper around a Playwright {@link Page} object,
 * representing a single browser tab and providing access to its underlying functionality.
 */
public class BrowserTab implements IBrowserTab {
    /**
     * The underlying Playwright Page instance associated with this tab.
     * <p>
     * Note: The getter for this field is automatically generated by Lombok's {@code @Getter} annotation.
     */
    @Getter
    private final Page page;
    @Getter
    private final IMouseActions mouseActions;

    /**
     * Constructs a new {@code BrowserTab} instance.
     *
     * @param page The Playwright {@link Page} object to be wrapped and managed by this tab.
     */
    public BrowserTab(Page page) {
        this.page = page;
        this.mouseActions = new MouseActions(page.mouse());
    }

    @Override
    public void handleNextAlert(Consumer<IAlert> alertHandler, Runnable actionThatTriggersAlert) {
        page.onceDialog(dialog -> alertHandler.accept(new BrowserAlert(dialog)));
        actionThatTriggersAlert.run();
    }

    @Override
    public IStorageManager getLocalStorage() {
        return new StorageManager(page.localStorage(), "Local Storage");
    }

    @Override
    public IStorageManager getSessionStorage() {
        return new StorageManager(page.sessionStorage(), "Session Storage");
    }

    @Override
    public String readClipboard() {
        Object result = page.evaluate("async () => await navigator.clipboard.readText()");
        return result != null ? result.toString() : "";
    }
}