package org.jcd2052.core.browser.browser;

import com.microsoft.playwright.Page;
import lombok.Getter;
import org.jcd2052.core.browser.browser.interfaces.IBrowserTab;

/**
 * Concrete implementation of the {@link IBrowserTab} interface.
 * <p>
 * This class serves as a wrapper around a Playwright {@link Page} object,
 * representing a single browser tab and providing access to its underlying functionality.
 */
public class BrowserTab implements IBrowserTab {

    /**
     * The underlying Playwright Page instance associated with this tab.
     * <p>
     * Note: The getter for this field is automatically generated by Lombok's {@code @Getter} annotation.
     */
    @Getter
    private final Page page;

    /**
     * Constructs a new {@code BrowserTab} instance.
     *
     * @param page The Playwright {@link Page} object to be wrapped and managed by this tab.
     */
    public BrowserTab(Page page) {
        this.page = page;
    }
}