package org.jcd2052.core.browser.browser;

import com.microsoft.playwright.Browser;
import com.microsoft.playwright.Page;
import lombok.Getter;
import lombok.Setter;
import org.jcd2052.core.browser.browser.interfaces.IBrowser;
import org.jcd2052.core.browser.browser.interfaces.IBrowserWindow;
import org.jcd2052.core.browser.configuration.IBrowserProperties;

import java.util.Collection;
import java.util.stream.Collectors;

/**
 * Concrete Playwright implementation of the {@link IBrowser} interface.
 * <p>
 * This class manages the lifecycle of a Playwright {@link Browser} instance,
 * including its contexts (windows), active state, and properties configuration.
 * <p>
 * Note: Getters for all fields in this class are automatically generated by Lombok's class-level {@code @Getter}.
 */
@Getter
public class PlaywrightBrowser implements IBrowser {
    /**
     * The raw Playwright Browser instance.
     */
    private final Browser browser;

    /**
     * The currently active browser window (context).
     * <p>
     * Note: The setter is automatically generated by Lombok's {@code @Setter}.
     */
    @Setter
    private IBrowserWindow currentBrowserWindow;

    /**
     * Flag indicating whether this browser instance has been closed.
     */
    private boolean isClosed;

    /**
     * The configuration properties used to initialize browser contexts.
     */
    private final IBrowserProperties browserProperties;

    /**
     * Constructs a new {@code PlaywrightBrowser} instance.
     *
     * @param browser           The raw Playwright {@link Browser} object to be wrapped.
     * @param browserProperties The configuration properties defining viewport size, tracing, etc.
     */
    public PlaywrightBrowser(Browser browser, IBrowserProperties browserProperties) {
        this.browser = browser;
        this.browserProperties = browserProperties;
        isClosed = false;
    }

    /**
     * {@inheritDoc}
     * <p>
     * <b>Implementation Note:</b> This method creates a new Playwright {@code BrowserContext},
     * applies the viewport dimensions specified in {@link IBrowserProperties}, and configures
     * it to ignore HTTPS errors by default.
     */
    @Override
    public IBrowserWindow openNewWindow() {
        BrowserWindow browserWindow = new BrowserWindow(browser.newContext(new Browser.NewContextOptions()
                .setViewportSize(browserProperties.getWidth(), browserProperties.getHeight())));
        setCurrentBrowserWindow(browserWindow);
        return browserWindow;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Collection<IBrowserWindow> getBrowserWindows() {
        return browser.contexts()
                .stream()
                .map(BrowserWindow::new)
                .collect(Collectors.toList());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getBrowserName() {
        return browser.browserType().name();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] takeScreenshot() {
        return getCurrentBrowserWindow()
                .getCurrentBrowserTab()
                .getPage()
                .screenshot(new Page.ScreenshotOptions().setFullPage(true));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void switchToWindow(IBrowserWindow window) {
        window.switchToTab(window.getCurrentBrowserTab());
        setCurrentBrowserWindow(window);
    }

    /**
     * {@inheritDoc}
     * <p>
     * Marks the internal {@code isClosed} flag as true after closing the Playwright browser.
     */
    @Override
    public void close() {
        browser.close();
        isClosed = true;
    }
}