package org.jcd2052.core.browser.services;

import lombok.Getter;

import org.jcd2052.core.browser.configuration.IBrowserProperties;
import org.jcd2052.core.browser.services.interfaces.IElementFactory;
import org.jcd2052.core.browser.services.interfaces.IElementFinderService;
import org.jcd2052.core.browser.services.interfaces.IElementSupplier;
import org.jcd2052.core.elements.ButtonElement;
import org.jcd2052.core.elements.CheckBoxElement;
import org.jcd2052.core.elements.DropdownElement;
import org.jcd2052.core.elements.ElementCollection;
import org.jcd2052.core.elements.ExpectedCount;
import org.jcd2052.core.elements.LabelElement;
import org.jcd2052.core.elements.LinkElement;
import org.jcd2052.core.elements.RadioButtonElement;
import org.jcd2052.core.elements.TextBoxElement;
import org.jcd2052.core.elements.UploadBox;
import org.jcd2052.core.elements.interfaces.IButtonElement;
import org.jcd2052.core.elements.interfaces.ICheckBoxElement;
import org.jcd2052.core.elements.interfaces.IDropdownElement;
import org.jcd2052.core.elements.interfaces.IElement;
import org.jcd2052.core.elements.interfaces.IElementCollection;
import org.jcd2052.core.elements.interfaces.ILabelElement;
import org.jcd2052.core.elements.interfaces.ILinkElement;
import org.jcd2052.core.elements.interfaces.IRadioButtonElement;
import org.jcd2052.core.elements.interfaces.ITextBoxElement;
import org.jcd2052.core.elements.interfaces.IUploadBox;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.HashMap;
import java.util.Map;

/**
 * Concrete implementation of the {@link IElementFactory} interface.
 * <p>
 * This Spring component serves as the central engine for creating UI elements in the framework.
 * It uses Java Reflection to dynamically map element interfaces (e.g., {@link IButtonElement})
 * to their concrete implementations (e.g., {@link ButtonElement}) at runtime.
 */
public class ElementFactory implements IElementFactory {
    /**
     * The service responsible for locating elements on the Playwright page.
     * <p>
     * Note: The getter is automatically generated by Lombok's {@code @Getter} annotation.
     */
    @Getter
    private final IElementFinderService elementFinderService;
    /**
     * The browser properties configuration.
     * <p>
     * Note: The getter is automatically generated by Lombok's {@code @Getter} annotation.
     */
    @Getter
    private final IBrowserProperties browserProperties;

    /**
     * Constructs a new {@code ElementFactory} instance.
     *
     * @param elementFinderService The service used to translate selectors into Playwright Locators.
     * @param browserProperties    The global browser configuration properties.
     */
    public ElementFactory(IElementFinderService elementFinderService, IBrowserProperties browserProperties) {
        this.elementFinderService = elementFinderService;
        this.browserProperties = browserProperties;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <T extends IElement> IElementCollection<T> createElementsCollection(
            String selector, String name, Class<T> clazz, ExpectedCount expectedCount) {
        return new ElementCollection<>(selector, name, clazz, this, expectedCount);
    }

    /**
     * {@inheritDoc}
     * <p>
     * <b>Implementation Note:</b> This method utilizes a reflection-based supplier
     * ({@link #getDefaultElementSupplier(Class)}) to instantiate the appropriate concrete element class.
     */
    public <T extends IElement> T createCustomElement(Class<T> clazz, String locator, String name) {
        IElementSupplier<T> elementSupplier = getDefaultElementSupplier(clazz);
        return createCustomElement(elementSupplier, locator, name);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <T extends IElement> IElementCollection<T> createChildElementsCollection(
            Class<T> elementClass, IElement parentElement, String selector, String name, ExpectedCount expectedCount) {
        String combinedSelector = combineSelectors(parentElement, selector);
        return new ElementCollection<>(combinedSelector, name, elementClass, this, expectedCount);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean isHighlightEnabled() {
        return browserProperties.isHighlight();
    }

    /**
     * Generates a default supplier that uses Reflection to instantiate a UI element.
     *
     * @param clazz The interface or concrete class of the element to create.
     * @param <T>   The element type.
     * @return An {@link IElementSupplier} capable of instantiating the requested element type.
     */
    private <T extends IElement> IElementSupplier<T> getDefaultElementSupplier(Class<T> clazz) {
        return (locator, name, elementFactory) -> {
            try {
                Constructor<T> ctor = resolveElementClass(clazz)
                        .getDeclaredConstructor(String.class, String.class, IElementFactory.class);
                ctor.setAccessible(true);
                T instance = ctor.newInstance(locator, name, this);
                ctor.setAccessible(false);
                return instance;
            } catch (NoSuchMethodException | InstantiationException | IllegalAccessException |
                     InvocationTargetException e) {
                throw new IllegalArgumentException("Something went wrong during element casting");
            }
        };
    }

    /**
     * Resolves an element interface to its concrete implementation class.
     * <p>
     * If a concrete class is passed, it is returned directly. If an interface is passed,
     * it looks up the mapped implementation in the registry.
     *
     * @param clazz The class or interface to resolve.
     * @param <T>   The element type.
     * @return The concrete class that implements the requested interface.
     * @throws IllegalArgumentException if an interface is requested that is not mapped in the registry.
     */
    private <T extends IElement> Class<T> resolveElementClass(Class<T> clazz) {
        if (clazz.isInterface() && !getElementTypesMap().containsKey(clazz)) {
            throw new IllegalArgumentException(
                    String.format("Interface %1$s is not found in getElementTypesMap()", clazz));
        }

        //noinspection unchecked
        return clazz.isInterface() ? (Class<T>) getElementTypesMap().get(clazz) : clazz;
    }

    /**
     * Provides the mapping registry between standard element interfaces and their concrete implementations.
     *
     * @return A map where the keys are element interfaces and the values are their concrete class equivalents.
     */
    protected Map<Class<? extends IElement>, Class<? extends IElement>> getElementTypesMap() {
        Map<Class<? extends IElement>, Class<? extends IElement>> typesMap = new HashMap<>();
        typesMap.put(IButtonElement.class, ButtonElement.class);
        typesMap.put(ILabelElement.class, LabelElement.class);
        typesMap.put(ITextBoxElement.class, TextBoxElement.class);
        typesMap.put(IDropdownElement.class, DropdownElement.class);
        typesMap.put(ILinkElement.class, LinkElement.class);
        typesMap.put(IRadioButtonElement.class, RadioButtonElement.class);
        typesMap.put(ICheckBoxElement.class, CheckBoxElement.class);
        typesMap.put(IUploadBox.class, UploadBox.class);
        return typesMap;
    }
}