package org.jcd2052.core.browser.services;

import lombok.Getter;
import org.jcd2052.core.browser.configuration.IBrowserProperties;
import org.jcd2052.core.browser.services.interfaces.IElementFactory;
import org.jcd2052.core.browser.services.interfaces.IElementFinderService;
import org.jcd2052.core.browser.services.interfaces.IElementSupplier;
import org.jcd2052.core.elements.ButtonElement;
import org.jcd2052.core.elements.CheckBoxElement;
import org.jcd2052.core.elements.DropdownElement;
import org.jcd2052.core.elements.ElementCollection;
import org.jcd2052.core.elements.ExpectedCount;
import org.jcd2052.core.elements.LabelElement;
import org.jcd2052.core.elements.LinkElement;
import org.jcd2052.core.elements.RadioButtonElement;
import org.jcd2052.core.elements.TextBoxElement;
import org.jcd2052.core.elements.UploadBox;
import org.jcd2052.core.elements.selector.Selector;
import org.jcd2052.core.elements.interfaces.IButtonElement;
import org.jcd2052.core.elements.interfaces.ICheckBoxElement;
import org.jcd2052.core.elements.interfaces.IDropdownElement;
import org.jcd2052.core.elements.interfaces.IElement;
import org.jcd2052.core.elements.interfaces.IElementCollection;
import org.jcd2052.core.elements.interfaces.ILabelElement;
import org.jcd2052.core.elements.interfaces.ILinkElement;
import org.jcd2052.core.elements.interfaces.IRadioButtonElement;
import org.jcd2052.core.elements.interfaces.ITextBoxElement;
import org.jcd2052.core.elements.interfaces.IUploadBox;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.HashMap;
import java.util.Map;

/**
 * Concrete implementation of the {@link IElementFactory} interface.
 * <p>
 * This class serves as the central engine for creating UI elements in the framework.
 * It uses Java Reflection to dynamically map element interfaces (e.g., {@link IButtonElement})
 * to their concrete implementations (e.g., {@link ButtonElement}) at runtime,
 * leveraging the Just-In-Time Selector locator strategies.
 * </p>
 */
public class ElementFactory implements IElementFactory {
    /**
     * The service responsible for locating elements dynamically on the Playwright page.
     * <p>
     * Note: The getter is automatically generated by Lombok's {@code @Getter} annotation.
     * </p>
     */
    @Getter
    private final IElementFinderService elementFinderService;
    /**
     * The browser properties configuration.
     * <p>
     * Note: The getter is automatically generated by Lombok's {@code @Getter} annotation.
     * </p>
     */
    @Getter
    private final IBrowserProperties browserProperties;
    private final Map<Class<? extends IElement>, Class<? extends IElement>> elementRegistry = new HashMap<>();

    /**
     * Constructs a new {@code ElementFactory} instance.
     *
     * @param elementFinderService The service used to evaluate Selector strategies into Playwright Locators.
     * @param browserProperties    The global browser configuration properties.
     */
    public ElementFactory(IElementFinderService elementFinderService, IBrowserProperties browserProperties) {
        this.elementFinderService = elementFinderService;
        this.browserProperties = browserProperties;
        registerDefaultElements();
    }

    @Override
    public <T extends IElement> IElementCollection<T> createElementsCollection(
            Selector selector,
            String name,
            IElementSupplier<T> supplier,
            ExpectedCount expectedCount) {
        return new ElementCollection<>(selector, name, this, supplier, expectedCount);
    }

    @Override
    public <T extends IElement> IElementCollection<T> createElementsCollection(
            Selector selector,
            String name,
            Class<T> clazz,
            ExpectedCount expectedCount) {
        return createElementsCollection(selector, name, getDefaultElementSupplier(clazz), expectedCount);
    }

    @Override
    public <T extends IElement> IElementCollection<T> createChildElementsCollection(
            IElementSupplier<T> supplier,
            IElement parentElement,
            Selector selector,
            String name,
            ExpectedCount expectedCount) {
        Selector combinedSelector = combineSelectors(parentElement, selector);
        return new ElementCollection<>(combinedSelector, name, this, supplier, expectedCount);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <T extends IElement> IElementCollection<T> createChildElementsCollection(
            Class<T> elementClass,
            IElement parentElement,
            Selector selector,
            String name,
            ExpectedCount expectedCount) {
        return createChildElementsCollection(
                getDefaultElementSupplier(elementClass),
                parentElement,
                selector,
                name,
                expectedCount);
    }

    /**
     * {@inheritDoc}
     * <p>
     * <b>Implementation Note:</b> This method utilizes a reflection-based supplier
     * ({@link #getDefaultElementSupplier(Class)}) to instantiate the appropriate concrete element class.
     * </p>
     */
    @Override
    public <T extends IElement> T createCustomElement(Class<T> clazz, Selector locator, String name) {
        IElementSupplier<T> elementSupplier = getDefaultElementSupplier(clazz);
        return createCustomElement(elementSupplier, locator, name);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean isHighlightEnabled() {
        return browserProperties.isHighlight();
    }

    /**
     * Registers a custom mapping between an element interface and its implementation.
     *
     * @param interfaceClass      The element interface contract.
     * @param implementationClass The concrete class implementing the interface.
     */
    public void registerElement(
            Class<? extends IElement> interfaceClass,
            Class<? extends IElement> implementationClass) {
        elementRegistry.put(interfaceClass, implementationClass);
    }

    /**
     * Generates a default supplier that uses Reflection to instantiate a UI element.
     * <p>
     * Searches for a constructor matching the signature: {@code (Selector locator, String name, IElementFactory factory)}.
     * </p>
     *
     * @param clazz The interface or concrete class of the element to create.
     * @param <T>   The element type.
     * @return An {@link IElementSupplier} capable of instantiating the requested element type.
     */
    private <T extends IElement> IElementSupplier<T> getDefaultElementSupplier(Class<T> clazz) {
        return (locator, name, elementFactory) -> {
            try {
                Constructor<T> ctor = resolveElementClass(clazz)
                        .getDeclaredConstructor(Selector.class, String.class, IElementFactory.class);
                ctor.setAccessible(true);
                T instance = ctor.newInstance(locator, name, this);
                ctor.setAccessible(false);
                return instance;
            } catch (NoSuchMethodException | InstantiationException | IllegalAccessException |
                     InvocationTargetException e) {
                throw new IllegalArgumentException("Something went wrong during element casting: " + e.getMessage(), e);
            }
        };
    }

    /**
     * Resolves an element interface to its concrete implementation class.
     * <p>
     * If a concrete class is passed, it is returned directly. If an interface is passed,
     * it looks up the mapped implementation in the registry.
     * </p>
     *
     * @param clazz The class or interface to resolve.
     * @param <T>   The element type.
     * @return The concrete class that implements the requested interface.
     * @throws IllegalArgumentException if an interface is requested that is not mapped in the registry.
     */
    private <T extends IElement> Class<T> resolveElementClass(Class<T> clazz) {
        if (clazz.isInterface() && !elementRegistry.containsKey(clazz)) {
            throw new IllegalArgumentException(
                    String.format("Interface %1$s is not found in getElementTypesMap()", clazz));
        }

        //noinspection unchecked
        return clazz.isInterface() ? (Class<T>) elementRegistry.get(clazz) : clazz;
    }

    /**
     * Registers the built-in core framework elements into the runtime element registry.
     */
    private void registerDefaultElements() {
        elementRegistry.put(IButtonElement.class, ButtonElement.class);
        elementRegistry.put(ILabelElement.class, LabelElement.class);
        elementRegistry.put(ITextBoxElement.class, TextBoxElement.class);
        elementRegistry.put(IDropdownElement.class, DropdownElement.class);
        elementRegistry.put(ILinkElement.class, LinkElement.class);
        elementRegistry.put(IRadioButtonElement.class, RadioButtonElement.class);
        elementRegistry.put(ICheckBoxElement.class, CheckBoxElement.class);
        elementRegistry.put(IUploadBox.class, UploadBox.class);
    }
}