package org.jcd2052.core.pages;

import lombok.AccessLevel;
import lombok.Getter;
import org.jcd2052.core.browser.services.interfaces.IElementFactory;
import org.jcd2052.core.elements.interfaces.IElement;
import org.jcd2052.core.elements.interfaces.ILabelElement;

import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;

/**
 * An abstract base class representing a distinct web form or page fragment.
 * <p>This class serves as a foundational building block for the Page Object Model (POM)
 * architecture. It utilizes a primary, unique {@link ILabelElement} (referred to as the
 * {@code formLabel}) to represent the root container or a uniquely identifying feature of
 * the form. All form-level synchronization methods (like waiting for visibility) are
 * delegated to this root element.</p>
 */
@Getter
public abstract class AbstractForm implements IForm {
    /**
     * The human-readable name of the form, used primarily for logging and reporting.
     */
    private final String name;
    /**
     * The root element or unique identifier for this form.
     * <p>Protected getter generated by Lombok.</p>
     */
    @Getter(value = AccessLevel.PROTECTED)
    private final ILabelElement formLabel;
    /**
     * The factory used to instantiate child elements within this form.
     * <p>Protected getter generated by Lombok.</p>
     */
    @Getter(value = AccessLevel.PROTECTED)
    private final IElementFactory elementFactory;

    /**
     * Constructs a new {@code AbstractForm}.
     *
     * @param locatorStrategy The Playwright selector used to uniquely identify the form's root or main label element.
     * @param name            The human-readable name of the form (e.g., "Login Form", "User Profile Section").
     * @param elementFactory  The {@link IElementFactory} responsible for creating the form's root label and any subsequent child elements.
     */
    protected AbstractForm(String locatorStrategy, String name, IElementFactory elementFactory) {
        this.name = name;
        this.elementFactory = elementFactory;
        this.formLabel = elementFactory.createLabelElement(locatorStrategy, name);
    }

    /**
     * Checks if the form is currently visible on the page.
     * <p>This evaluation is delegated to the underlying {@code formLabel} element.</p>
     *
     * @return {@code true} if the form is visible; {@code false} otherwise.
     */
    @Override
    public boolean isVisible() {
        return getFormLabel().isVisible();
    }

    /**
     * Waits for the form to finish loading.
     * <p>This synchronization is delegated to the underlying {@code formLabel} element's
     * specific loading wait condition.</p>
     *
     * @return {@code true} if the form successfully loaded within the timeout period.
     */
    public boolean waitForLoading() {
        getFormLabel().waitForReadyState();
        return getFormLabel().waitForLoading();
    }

    /**
     * Waits for the form to become visible on the page.
     * <p>This synchronization is delegated to the underlying {@code formLabel} element.</p>
     *
     * @return {@code true} if the form became visible within the timeout period.
     */
    public boolean waitToBeVisible() {
        return getFormLabel().waitToBeVisible();
    }

    /**
     * Waits for the form to become invisible or detached from the DOM.
     * <p>This synchronization is delegated to the underlying {@code formLabel} element's
     * detached state condition, which is useful for verifying that a form (like a modal
     * or popup) has successfully closed.</p>
     *
     * @return {@code true} if the form became invisible/detached within the timeout period.
     */
    @Override
    public boolean waitToBeInvisible() {
        return getFormLabel().waitToBeDetached();
    }

    protected Map<String, IElement> getAllElements() {
        Map<String, IElement> elementsMap = new HashMap<>();
        Class<?> currentClass = this.getClass();
        while (currentClass != null && currentClass != Object.class) {

            for (Field field : currentClass.getDeclaredFields()) {
                if (IElement.class.isAssignableFrom(field.getType())) {
                    try {
                        field.setAccessible(true);
                        IElement element = (IElement) field.get(this);

                        if (element != null) {
                            elementsMap.put(field.getName(), element);
                        }
                    } catch (IllegalAccessException e) {
                        throw new RuntimeException(
                                "Failed to read element field via reflection: " + field.getName(), e);
                    } finally {
                        field.setAccessible(false);
                    }
                }
            }
            currentClass = currentClass.getSuperclass();
        }

        return elementsMap;
    }
}